services:
  - type: web
    name: turnify-pro-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: FIREBASE_CREDENTIALS_JSON
        sync: false
      - key: GEMINI_API_KEY
        sync: false
