# Generated by Django 6.0.3 on 2026-03-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='assigned_employee',
            field=models.CharField(blank=True, help_text='Employee assigned to this turn', max_length=100),
        ),
        migrations.AddField(
            model_name='turn',
            name='priority',
            field=models.IntegerField(default=0, help_text='Priority level for VIP customers'),
        ),
        migrations.AddField(
            model_name='turn',
            name='service_type',
            field=models.CharField(default='general', help_text='Type of service: general, preferential, emergency', max_length=50),
        ),
    ]
