# Generated by Django 6.0.6 on 2026-06-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0002_turn_assigned_employee_turn_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='required_documents',
            field=models.JSONField(blank=True, default=list, help_text='Documents required by employee'),
        ),
        migrations.AddField(
            model_name='turn',
            name='uploaded_documents',
            field=models.JSONField(blank=True, default=list, help_text='Documents uploaded by user'),
        ),
    ]
