# Generated by Django 6.0.5 on 2026-06-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0003_turn_required_documents_turn_uploaded_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(default='client', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
