# Generated by Django

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('turns', '0004_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='register',
            name='cedula',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='register',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]