# Generated by Django 6.0.6 on 2026-06-26 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0005_register_add_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='cargo',
            field=models.CharField(blank=True, default='', help_text='Position/Grade', max_length=100),
        ),
        migrations.AddField(
            model_name='register',
            name='document_type',
            field=models.CharField(default='CC', help_text='CC, CE, PA, NIT', max_length=20),
        ),
        migrations.AddField(
            model_name='register',
            name='entidad',
            field=models.CharField(blank=True, default='', help_text='Entity', max_length=200),
        ),
        migrations.AddField(
            model_name='register',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='register',
            name='sede',
            field=models.CharField(blank=True, default='', help_text='Office/Branch', max_length=200),
        ),
        migrations.AddField(
            model_name='turn',
            name='documents_approved',
            field=models.IntegerField(default=0, help_text='Count of approved documents'),
        ),
        migrations.AddField(
            model_name='turn',
            name='documents_pending',
            field=models.IntegerField(default=0, help_text='Count of pending documents'),
        ),
        migrations.AddField(
            model_name='turn',
            name='documents_rejected',
            field=models.IntegerField(default=0, help_text='Count of rejected documents'),
        ),
        migrations.AddField(
            model_name='turn',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turn',
            name='service_type',
            field=models.CharField(default='general', help_text='Type of service: general, preferential, emergency, virtual', max_length=50),
        ),
    ]
