# Generated by Django 6.0 on 2026-06-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0006_register_cargo_register_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='sede',
            field=models.CharField(blank=True, default='MOSQUERA', help_text='Office location', max_length=100),
        ),
    ]
