# Generated by Django 6.0 on 2026-06-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0009_add_created_by_to_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turn',
            name='created_by',
            field=models.CharField(blank=True, default='', help_text='Username who requested this turn', max_length=100, null=True),
        ),
    ]
