# Generated by Django 6.0 on 2026-06-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0010_fix_created_by_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, help_text='Date/time for rescheduled turn', null=True),
        ),
    ]
